ARecSys/urls.py
"""ARecSys URL Configuration
"""
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from apps.user_authentication import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.main.urls')),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html', redirect_authenticated_user=True),
         name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/main/models.py
from django.contrib.auth.models import User
from django.core.validators import MinLengthValidator
from django.db import models


class Anime(models.Model):
    class Meta:
        verbose_name = "anime info"

    anime_id = models.IntegerField(verbose_name='ID of Anime', primary_key=True, db_index=True)

    title = models.CharField(verbose_name="Title in Japanese", max_length=100)
    title_eng = models.CharField(verbose_name="Title in English", max_length=100, blank=True, null=True)

    synopsis = models.TextField(verbose_name="Summary (Synopsis)", validators=[MinLengthValidator(limit_value=100)])

    episodes = models.IntegerField(verbose_name="Number of Episodes", blank=True, null=True)

    premiered = models.TextField(verbose_name="Premiered", blank=True)

    rating = models.TextField(verbose_name="Ratings", blank=True)

    score = models.FloatField(verbose_name="Weighted Score", null=True, blank=True)
    scored_by = models.IntegerField(verbose_name="Scored By", null=True, blank=True)

    rank = models.IntegerField(verbose_name="Overall Rank", null=True)
    popularity = models.IntegerField(verbose_name="Overall Popularity", null=True, blank=True)
    members = models.IntegerField(verbose_name="Members", null=True)

    source = models.CharField(verbose_name="Source of Anime", max_length=25, null=True)

    image = models.URLField(verbose_name="Image URL")

    def as_dict(self):
        data = {
            'id': self.anime_id,
            'title': self.title,
            'title_english': self.title_eng,
            'synopsis': self.synopsis,
            'episodes': self.episodes,
            'score': self.score,
            'scored_by': self.scored_by,
            'image': self.image,
            'genres': []
        }

        genres = self.genre.all()
        for genre in genres:
            data['genres'].append(genre.name)

        return data

    def __str__(self):
        return f"{self.anime_id} {self.title}"


class Genre(models.Model):
    class Meta:
        verbose_name = "anime genre"

    anime = models.ForeignKey(Anime, verbose_name="anime info", related_name="genre", on_delete=models.CASCADE)
    name = models.CharField(verbose_name="Name of Genre", max_length=20)

    def __str__(self):
        return f"{self.name}"


class AnimeScore(models.Model):
    class Meta:
        verbose_name = "anime score"

    anime = models.OneToOneField(Anime, verbose_name="Anime", related_name="anime_score", on_delete=models.CASCADE,
                                 primary_key=True)
    username = models.ForeignKey(User, verbose_name="User", related_name="user_score", on_delete=models.CASCADE)
    user_anime_score = models.IntegerField(verbose_name="My Score")

    def __str__(self):
        return f"{self.username.username} - {self.anime.title}:{self.user_anime_score}"

    def as_dict(self):
        data = {
            'id': self.anime_id,
            'title': self.anime.title,
            'rank': self.anime.rank,
            'image': self.anime.image,
            'ua_score': self.user_anime_score
        }

        return data

templates/anime_detail.html
{% extends 'base.html' %}
{% load static %}

{% block titleBlock %}
    <title>{{  anime.title }}</title>
{% endblock %}

{% block contentblock %}
    <section class="hero-wrap hero-wrap-2" style="background-image: url({% static 'main/images/detail.jpg' %});">
        <div class="overlay"></div>
        <div class="container">
            <div class="row no-gutters slider-text align-items-end justify-content-center">
                <div class="col-md-9 pb-5 text-center">
                    <h1 class="mb-3 title">
                        <span class="title">
                            <span class="name">
                                {{ anime.title }}
                            </span>
                            <br>
                            <span class="title-eng">
                                {{ anime.title_eng }}
                            </span>
                        </span>
                    </h1>
                </div>
            </div>
        </div>
    </section>

    <section class="ftco-section">
      <div class="container">
        <div class="row">
          <div class="col-lg-8 order-lg-last">
              <h2>Synopsis</h2>
                <hr>
              <p>{{ anime.synopsis }}</p>
            <div class="tag-widget post-tag-container mb-5 mt-5">
              <div class="tagcloud">
                <h2>Genre</h2>
                <hr>
                {% for genre in anime.genre.all %}
                    <a href="#" class="tag-cloud-link">{{ genre.name }}</a>
                {% endfor %}
              </div>
            </div>
            <div class="tag-widget post-tag-container mb-5 mt-5">
                <div class="tagcloud">
                    <h2>Recommendation</h2>
                    <hr>
                    <a href="{% url 'recommend-anime' anime.anime_id %}">Get Recommendation</a>
                </div>
            </div>
            <div class="tag-widget post-tag-container mb-5 mt-5">
              <div class="tagcloud">
                <h2>My Score: {{ my_score }}</h2>
                <hr>
                <form method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        {{form.user_anime_score}}
                    </div>
                    <button type="submit" class="btn btn-primary">Submit</button>
                    <input type="hidden" name="anime" id="id_anime" value="{{ anime.anime_id }}">
                </form>

              </div>
            </div>
          </div> <!-- .col-md-8 -->
          <div class="col-lg-4 sidebar pr-lg-5">
            <div class="sidebar-box">
                <img src={{ anime.image }} alt="" class="img-fluid image flex">
            </div>
            <div class="sidebar-box">
                <div class="container-information">
                    <h2 class="heading">Information</h2>
                    <hr />
                    <div>
                        <span class="cont_text">Episodes:</span>
                        {% if anime.episodes %}
                            {{ anime.episodes }}
                        {% else %}
                            Not Found
                        {% endif %}
                    </div>
                    <div>
                        <span class="cont_text">Premiered: </span>
                        {% if anime.premiered %}
                            {{ anime.premiered }}
                        {% else %}
                            Not Found
                        {% endif %}
                    </div>
                    <div>
                        <span class="cont_text">Source: </span>
                        {% if anime.source %}
                            {{ anime.source }}
                        {% else %}
                            Not Found
                        {% endif %}
                    </div>
                    <div>
                        <span class="cont_text">Rating: </span>
                        {% if anime.rating %}
                            {{ anime.rating }}
                        {% else %}
                            Not Found
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="sidebar-box">
                <div class="container-stats">
                    <h2 class="heading">Statistics</h2>
                    <hr />
                    <div>
                        <span class="cont_text">Score: </span>
                        {% if anime.score %}
                            {{ anime.score }} (scored by {{ anime.scored_by }} people)
                        {% else %}
                            Not Found
                        {% endif %}
                    </div>
                    <div>
                        <span class="cont_text">Rank: </span>
                        {% if anime.rank %}
                            #{{ anime.rank }}
                        {% else %}
                            Not Found
                        {% endif %}
                    </div>
                    <div>
                        <span class="cont_text">Popularity: </span>
                        {% if anime.popularity %}
                            {{ anime.popularity }}
                        {% else %}
                            Not Found
                        {% endif %}
                    </div>
                </div>
            </div>
          </div>
        </div>
      </div>
    </section>
{% endblock contentblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% block titleBlock %}
    {% endblock %}
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'main/fonts/icomoon/style.css' %}">
    {% block stylesheet %}
    {% endblock %}
    <link rel="stylesheet" href="{% static 'main/css/base.css' %}">
</head>
<body>
    <div class="site-mobile-menu site-navbar-target">
        <div class="site-mobile-menu-header">
            <div class="site-mobile-menu-close mt-3">
                <span class="icon-close2 js-menu-toggle"></span>
            </div>
        </div>
        <div class="site-mobile-menu-body"></div>
    </div>

    <header class="site-navbar py-4 js-sticky-header site-navbar-target" role="banner">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-6 col-xl-2">
                    <h1 class="mb-0 site-logo m-0 p-0">
                        <a href="{% url 'index' %}" class="mb-0">ARecSys</a>
                    </h1>
                </div>

                <div class="col-12 col-md-10 d-none d-xl-block">
                    <nav class="site-navigation position-relative text-right" role="navigation">
                        <ul class="site-menu main-menu js-clone-nav mr-auto d-none d-lg-block">
                            <li><a href="{% url 'index' %}" class="nav-link">Home</a></li>
                            {% if user.is_authenticated %}
                                <li><a href="{% url 'profile' %}" class="nav-link">Profile</a></li>
                                <li><a href="{% url 'logout' %}?next={{request.path}}" class="nav-link">Logout</a></li>
                            {% else %}
                                <li><a href="{% url 'login' %}?next={{request.path}}" class="nav-link">Login</a></li>
                                <li><a href="{% url 'register' %}" class="nav-link">Register</a></li>
                            {% endif %}
                        </ul>
                    </nav>
                </div>
                <div class="col-6 d-inline-block d-xl-none ml-md-0 py-3">
                    <a href="#" class="site-menu-toggle js-menu-toggle text-white float-right">
                        <span class="icon-menu h3"></span>
                    </a>
                </div>
            </div>
        </div>
    </header>

    {% block contentblock %}
    {% endblock %}

    <!-- Footer -->
    <footer class="site-footer">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="row">
              <div class="col-md-8">
                <h2 class="footer-heading mb-4">About ARecSys</h2>
                <p>This project was developed by Yash Sharma and Ashish Jha under the guidance of Profressor Filippov Evgeny Vasilyevich for the subject Software Developement </p>
                  <p>
                      Yash Sharma and Ashish Jha
                      <br>
                      Masters Student
                      <br>
                      Faculty of Computer Science and Technology
                      <br>
                      Saint Petersburg Electrotechnical University "LETI"
                      <br>
                      Saint Petersburg, Russian Federation
                  </p>
              </div>
              <div class="col-md-4 mx-auto">
                <h2 class="footer-heading mb-4">Quick Links</h2>
                <ul class="list-unstyled">
                    <li><a href="https://etu.ru/">ETU LETI</a></li>
                    <li><a href="https://github.com/Yashs744">Expert #1 (Yash Sharma)</a></li>
                    <li><a href="https://github.com/murdockbleak">Expert #2 (Ashish Jha)</a></li>
                </ul>
              </div>

            </div>
          </div>
        </div>
        <div class="row pt-5 mt-5 text-center">
          <div class="col-md-12">
            <div class="border-top pt-5">
            <p class="copyright">
            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
            Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="icon-heart text-danger" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank" >Colorlib</a>
            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
            </p>
            </div>
          </div>

        </div>
      </div>
    </footer>

    <script src="{% static "main/js/jquery-3.3.1.min.js" %}"></script>
    <script src="{% static "main/js/bootstrap.min.js" %}"></script>

    <script src="{% static 'main/js/base.js'%}"></script>
    {% block blockScripts %}
    {% endblock %}
</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block titleBlock %}
    <title>Anime Recommendation</title>
{% endblock %}

{% block contentblock %}
    <div class="site-block-wrap">
        <div class="owl-carousel with-dots">
            <div class="site-blocks-cover overlay overlay-2"
                 style="background-image: url('{% static "main/images/backImage.jpg" %}')" data-aos="fade" id="home-section">

                <div class="container">
                    <div class="row align-items-center justify-content-center">
                        <div class="col-md-12 mt-lg-8 text-center">
                            <h1 class="text-shadow">Anime Recommender System </h1>
                            <p class="mb-5 text-shadow">
                                Anime Recommendation based using Anime Synopsis, Genre and Ratings.<br/>
                            </p>
                            <form id="input_box" action='/' method="post">
                                <div class="form-group">
                                {% csrf_token %}
                                {{ form.anime_name }}
                                </div>
                                <button type="submit" id = "getSimilar" name="search" class="btn btn-primary">Search</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Main -->
    {% if animes %}
    <section class="ftco-section">
        <div class="container">
            {% for anime in animes %}
                <div class="row">
                    <div class="col-lg-8 order-lg-last">
                        <h3><a href="{% url 'anime-detail' anime.id %}">{{ anime.title }}
                            {% if anime.title_english %}
                                ({{ anime.title_english }})</a>
                            {% else %}
                                </a>
                            {% endif %}
                        </h3>
                        <h2>Synopsis</h2>
                        <hr>
                        <p>{{ anime.synopsis }}</p>
                        <div class="tag-widget post-tag-container mb-5 mt-5">
                            <div class="tagcloud">
                                <h2>Genre</h2>
                                <hr>
                                {% for genre in anime.genres %}
                                    <a href="#" class="tag-cloud-link">{{ genre }}</a>
                                {% endfor %}
                            </div>
                        </div>
                        <div class="tag-widget post-tag-container mb-5 mt-5">
                            <div class="tagcloud">
                                <h2>Recommendation</h2>
                                <hr>
                                <a href="{% url 'recommend-anime' anime.id %}">Get Recommendation</a>
                            </div>
                        </div>
                    </div> <!-- .col-md-8 -->
                    <div class="col-lg-4 sidebar pr-lg-5">
                        <div class="sidebar-box">
                            <img src={{ anime.image }} alt="" class="img-fluid image flex">
                        </div>
                    </div>
                </div>
                <br/>
                <hr/>
                <br/>
            {% endfor %}
        </div>
    </section>
    {% endif %}

{% endblock %}

templates/login.html
{% extends 'base.html' %}
{% load static %}

{% block titleBlock %}
    <title>Login</title>
{% endblock %}
{% block stylesheet %}
    <link rel="stylesheet" type="text/css" href="{% static 'main/css/util.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'main/css/ua.css' %}">
{% endblock %}

{% block contentblock %}
	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100">
				<form class="login100-form validate-form" method="post" action="">
					<span class="login100-form-title p-b-43">
						Login to continue
					</span>
                    {% csrf_token %}
					<div class="wrap-input100 validate-input">
                        {{ form.username }}
						<span class="focus-input100"></span>
						<span class="label-input100">Username</span>
					</div>

					<div class="wrap-input100 validate-input">
						{{ form.password }}
						<span class="focus-input100"></span>
						<span class="label-input100">Password</span>
					</div>

                    {{ form.non_field_errors }}

					<div class="container-login100-form-btn">
						<button class="login100-form-btn">
							Login
						</button>
					</div>

                    <div class="border-top pt-2">
                        <small class="text-muted">
                            Need An Account? <a class="ml-2" href="{% url 'register' %}">Sign Up Now</a>
                        </small>
                    </div>
				</form>

				<div class="login100-more" style="background-image: url('{% static "main/images/login.jpg" %}');"></div>
			</div>
		</div>
	</div>

{% endblock %}

{% block blockScripts %}
    <script src="{% static 'main/js/main.js'%}"></script>
{% endblock %}

templates/profile.html
{% extends 'base.html' %}
{% load static %}


{% block titleBlock %}
    <title>{{ user.userprofile }}</title>
{% endblock %}
{% block stylesheet %}
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'main/css/profile.css' %}">
{% endblock %}

{% block contentblock %}
    <section class="ftco-section" style="background: #F8F8F8;">
        <div class="container">
            <div class="row">
                <div class="col-lg-4">
                    <div class="card card-profile">
                        <div style="background-image: url({% static 'main/images/profile_background.jpg' %});" class="card-header"></div>
                        <div class="card-body text-center"><img src="{{ user.userprofile.image.url }}" class="card-profile-img">
                            <h3 class="mb-3">{{ user.username }}</h3>
                            <p class="mb-4">{{ user.bio }}</p>
                        </div>
                    </div>
                </div>
                <div class="col-lg-8">
                    <div class="card">
                        {% if animes %}
                            <div class="list-group card-list-group">
                                <div class="list-group-item py-5">
                                    <h3 class="card-title">Anime</h3>
                                    <div class="media">
                                        <div class="media-body">
                                            <table class="media-table">
                                                <tbody>
                                                <tr class="list-table-header">
                                                    <th class="header-title status"></th>
                                                    <th class="header-title number">#</th>
                                                    <th class="header-title timage">Image</th>
                                                    <th class="header-title ttitle">Title</th>
                                                    <th class="header-title rank">Rank</th>
                                                    <th class="header-title score">Score</th>
                                                </tbody>
                                                {% for anime in animes %}
                                                    <tbody class="list-item">
                                                    <tr class="list-table-data">
                                                        <td class="data status watching"></td>
                                                        <td class="data number">{{ anime.num }}</td>
                                                        <td class="data img">
                                                            <a href="{% url 'anime-detail' anime.id %}" class="link">
                                                                <img src="{{ anime.image }}" class="hover-info img">
                                                            </a>
                                                        </td>
                                                        <td class="data ttitle clearfix">
                                                            <a href="{% url 'anime-detail' anime.id %}" class="link">
                                                                {{ anime.title }}
                                                            </a>
                                                        </td>
                                                        <td class="data rank">
                                                            {% if anime.rank %}
                                                                {{ anime.rank }}
                                                            {% else %}
                                                                -
                                                            {% endif %}
                                                        </td>
                                                        <td class="data score">
                                                            {{ anime.ua_score }}
                                                        </td>
                                                        </tr>
                                                    </tbody>
                                                {% endfor %}
                                            </table>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% else %}
                            <div class="px-3 my-3 text-center">
                                <h4><a href="{% url 'index' %}">Start Scoring Animes</a></h4>
                            </div>
                        {% endif %}
                    </div>
                    <form class="card" method="post" enctype="multipart/form-data">
                        <div class="card-body">
                            <h3 class="card-title">Edit Profile</h3>
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group mb-4">
                                        <label class="form-label">Email address</label>
                                        {{ u_form.email }}
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group mb-4">
                                        <label class="form-label">Bio</label>
                                        {{p_form.bio }}
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group mb-4">
                                        <label class="form-label">Profile Photo</label>
                                        {{ p_form.image }}
                                        {% if p_form.image.errors %}
                                            <p class=" label label-danger">
                                                {{ p_form.image.errors }}
                                            </p>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="card-footer text-center">
                            <button type="submit" class="btn btn-primary">Update Profile</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
{% endblock contentblock %}

templates/recommend.html
{% extends 'base.html' %}
{% load static %}

{% block titleBlock %}
    <title>Anime Recommendation</title>
{% endblock %}

{% block contentblock %}

    <section class="hero-wrap hero-wrap-2" style="background-image: url({% static 'main/images/recommend.jpg' %});">
        <div class="overlay"></div>
        <div class="container">
            <div class="row no-gutters slider-text align-items-end justify-content-center">
                <div class="col-md-9 pb-5 text-center">
                    <h1 class="mb-3 title">
                        <span class="title">
                            <span class="name">
                                Recommendations
                            </span>
                            <br>
                        </span>
                    </h1>
                </div>
            </div>
        </div>
    </section>

    <!-- Main -->
    <section class="ftco-section">
        <div class="container">
            {% if animes %}
                {% for anime in animes %}
                    <div class="row">
                        <div class="col-lg-8 order-lg-last">
                            <h3><a href="{% url 'anime-detail' anime.id %}">{{ anime.title }}
                                {% if anime.title_english %}
                                    ({{ anime.title_english }})</a>
                                {% else %}
                                    </a>
                                {% endif %}
                            </h3>
                            <h2>Synopsis</h2>
                            <hr>
                            <p>{{ anime.synopsis }}</p>
                            <div class="tag-widget post-tag-container mb-5 mt-5">
                                <div class="tagcloud">
                                    <h2>Genre</h2>
                                    <hr>
                                    {% for genre in anime.genres %}
                                        <a href="#" class="tag-cloud-link">{{ genre }}</a>
                                    {% endfor %}
                                </div>
                            </div>
                            <div class="tag-widget post-tag-container mb-5 mt-5">
                                <div class="tagcloud">
                                    <h2>Recommendation</h2>
                                    <hr>
                                    <a href="{% url 'recommend-anime' anime.id %}">Get Recommendation</a>
                                </div>
                            </div>
                        </div> <!-- .col-md-8 -->
                        <div class="col-lg-4 sidebar pr-lg-5">
                            <div class="sidebar-box">
                                <img src={{ anime.image }} alt="" class="img-fluid image flex">
                            </div>
                        </div>
                    </div>
                    <br/>
                    <hr/>
                    <br/>
                {% endfor %}
            {% endif %}
        </div>
    </section>
{% endblock %}